export const LOS_NAMES: string[] = [
  "Anders Andrè Andersen",
  "Anders Melingen",
  "Anders Norstrand",
  "Anders Sangolt",
  "Are Aksnes",
  "Arild Lofthus",
  "Arne Gunnleiv Sæthre",
  "Arne Halvorsen",
  "Arnfinn Olav Remøy",
  "Arnt Egil Bjellvåg",
  "Arve Bjørnulf Bøe",
  "Arve Gangåssæter",
  "Asbjørn Austevoll",
  "Asbjørn Birkeli",
  "Audun Olsen",
  "Bent Elias Berntsen",
  "Bjarte Hindenes",
  "Bjarte Røksund",
  "Bjørn Helge Hjelmeland",
  "Bjørn Richard Abrahamsen",
  "Bjørnar Sæther",
  "Bård Magne Lunde",
  "Carl Ellingsen",
  "Christian Wilhelmsen",
  "Dag-Erik Kvalheim",
  "Dagfinn Fjeldstad",
  "Dagfinn Olsen",
  "Eirik Eriksen",
  "Eivind Sangolt",
  "Erlend Vik",
  "Espen Alsaker",
  "Espen Johnsen",
  "Frank-Roy Moltu",
  "Frode Arnesen",
  "Frode Møllerhaug",
  "Gaute Dyregro Haukeland",
  "Geir Bøe",
  "Geir Heggeset",
  "Geir Ognøy",
  "Geir Pettersen",
  "Geir Sigve Thorsen",
  "Geir-Arne Jensen",
  "Geirmund Stormark",
  "Gisle Aasebø",
  "Hallvard Nygård",
  "Halvard Grøneng",
  "Halvard Høydalsvik",
  "Hans-Arne Fylkesnes",
  "Hans Christian Ådlandsvik",
  "Harald Magne Bakken",
  "Helge Didriksen",
  "Holger Kåre Pettersen",
  "Håvar Sandvik",
  "Idar Moldøen",
  "Inge Johan Fagerheim",
  "Inge Olaissen",
  "Inge Ottar Sætrevik",
  "Jan Erik Fjeldsbø",
  "Jan Erik Lerum",
  "Jan I Nilsen",
  "Jan Kenneth Flygansvær",
  "Jan Magne Fosse",
  "Jan Ola Flåhammer",
  "Jan Ståle Sørensen",
  "Jan Terje Skåtevik",
  "Jan Vevatne",
  "John Petter Strand",
  "John Sigurd Torvik",
  "Jon Inge Nilsen",
  "Jon Aasberg",
  "Jon Sigurd Trovik",
  "Jostein Galtung",
  "Jostein Larsen",
  "Karl Andreas Njåstad",
  "Karl Helge Haagensen",
  "Karstein Helge Økland",
  "Ken Tommy Pettersen",
  "Kenneth Eilif Karlsen",
  "Kenneth Sandmo",
  "Kjell Arne Nes",
  "Kjell Evensen",
  "Kjell-Inge Telle",
  "Kjetil Magnussen",
  "Knut Arne Mikalsen",
  "Knut Egil Dyngeland",
  "Knut Inge Melingen",
  "Knut Steffensen",
  "Kristoffer Eidissen",
  "Kristian Bratthammer",
  "Kristian Valberg",
  "Lars Engvik",
  "Laurits Sund",
  "Leif Morten Slotvik",
  "Martin Jensen",
  "Martin Strømdahl",
  "Modstein Hansen",
  "Morten G. Urheim",
  "Morten Gunnar Telle",
  "Oddbjørn Snorre Hårsvær",
  "Odd Marvin Holberg",
  "Odd Roger Grinde",
  "Ola Moen",
  "Ole Andreas Vatle-Dahl",
  "Ole J. Henjesand",
  "Ole Magnus Benestvedt",
  "Ole Wille",
  "Onar Jøsang",
  "Ottar Eide",
  "Ove Arild Alfheim",
  "Ove Henning Smelvær",
  "Ove Valderhaug",
  "Per Herman Syre",
  "Per Morten Brennvik",
  "Remi Endre Hagenes",
  "Roger Notøy",
  "Roger Vik",
  "Rolf Magne Hausken",
  "Ronald Rydningen",
  "Ronny Stokkan",
  "Roy Pedersen",
  "Sigbjørn Tjoflot",
  "Sindre Myhre",
  "Solgunn Breivik Homme",
  "Staale Lemvig",
  "Stian Fonnes",
  "Stig Petter Midtbø",
  "Ståle Fagerstad",
  "Svein Austrheim",
  "Svein Boge",
  "Svein Egil Monsen",
  "Svein Henning Waagene",
  "Terje Mjølsvik",
  "Terje Sudmann",
  "Torbjørn Vinnes",
  "Tore Anton Årvik",
  "Tore Espeland",
  "Tore Hella",
  "Tore Lund",
  "Tore Nystøyl",
  "Tormod Sivertsen",
  "Torry Sakkariassen",
  "Trond Myklevoll",
  "Trond Nybakk",
  "Tronn Stadsøy",
  "Vegard Hatland",
  "Vermund Halhjem",
  "Vidar Undertun",
  "Willy Olsen",
  "Ørjan Boge",
  "Ørjan Østrem",
  "Øystein Handegård",
  "Øystein Hesthamar",
].sort((a, b) => a.localeCompare(b, "nb-NO"));

export type Booking = {
  id: string;
  vesselName: string;
  date: string;
  orderNumber: string;
  base: string | null;
  pilots: string[];
  gt: number | null;
  terminal?: string | null;
  createdAt?: number | null;
};

export const EMPTY_BOOKING: Booking = {
  id: "",
  vesselName: "",
  date: new Date().toISOString().slice(0, 10),
  orderNumber: "",
  base: "",
  pilots: [],
  gt: null,
  terminal: null,
  createdAt: null,
};

export const formatDate = (dateStr: string) => new Date(dateStr).toLocaleDateString("nb-NO");

export type Location = "Mongstad" | "Sture" | "Melkøya" | "Kårstø" | "Los øvrig" | "Nyhamna";
export type LosType = "Båt" | "Rigg";
